modLoader="javafml" #mandatory
	
loaderVersion="[35,)" #mandatory 

license="All rights reserved"

[[mods]] #mandatory
	
modId="bedwars" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Bedwars" #mandatory

logoFile="" #optional

credits="Thanks for downloading my Mod" #optional
	
authors="Luis" #optional

description='''

'''
	
[[dependencies.bedwars]] #optional
	
    modId="forge" #mandatory
    
    mandatory=true #mandatory
    
    versionRange="[35,)" #mandatory
    
    ordering="NONE"
    
    side="BOTH"
    
[[dependencies.bedwars]]
		
    modId="minecraft"
    
    mandatory=true

    versionRange="[1.16.4,1.17)"
    
    ordering="NONE"
    
    side="BOTH"
